# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "../images/hirsute-server-cloudimg-amd64-vagrant.box"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
  
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  config.vm.synced_folder "../projekte", "/home/vagrant/projekte"
  config.vm.synced_folder "../vagrant_data", "/home/vagrant/vagrant_data"


  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
    vb.name = "vagrant_vm"
	vb.memory = 1024
	vb.cpus = 1

  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
	sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu hirsute stable" -y
	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8
	sudo apt-get update
	sudo apt-get install docker-ce -y
    #sudo usermod -aG docker ${USER}
    sudo usermod -aG docker vagrant
	sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
  SHELL
end
